Sprint 1
loosq/middle.messenger.praktikum.yandex pull request #1
Opened 2022-01-17 10:23 UTC by loosq

2022-01-21 21:00 UTC, DmitryKhitrin requested changes
Привет, спасибо за отличную работу!) Все выглядит хорошо, кроме работы с svg,  давайте все же попробуем не расходовать трафик пользователя и импортируем иконки через use)

2022-01-22 20:56 UTC, loosq commented on .postcssrc
> +}
добавил

2022-01-23 08:36 UTC, loosq commented on index.js
> +const {DEFAULT_PORT, BUILD_PATH} = require('./constants');
добавил

2022-01-23 08:36 UTC, loosq commented on src/components/modal/modal.css
> +}
добавил линтер

2022-01-23 08:37 UTC, loosq commented on src/pages/chat/chat.css
> +    background: #EFEFEF;
добавил в переменную

2022-01-23 08:40 UTC, loosq commented on src/pages/chat/chat.pug
> +        ul
согласен, но кажется что сейчас нет смысла собирать эти данные в массив, решил подождать момента когда уже будем прокидывать данные и тогда отрисую весь список через ич. Частенько элементы списка могут быть с разными стилями и кажется целесообразным сохранить вариации разных элементов, что бы не забыть классы.

2022-01-23 08:42 UTC, loosq commented on src/pages/chat/chat.pug
> +              svg(width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg")
собрал в спрайт свгшки, ещё погуглил на счёт автоматизации этого, кажется нужно вытащить сборку в отдельный файл что бы нормально его конфигурировать. Решил сейчас не заморачиваться, далее вроде вебпак будет, там этот процесс на много проще выглядит судя по доке

2022-01-23 08:42 UTC, loosq commented on src/pages/chat/chat.pug
> +        svg(width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg")
сделано

2022-01-24 10:51 UTC, DmitryKhitrin approved these changes
Супер, спасибо за внесенные правки) Работу принимаю!)

2022-01-31 10:23 UTC, merged