Sprint 3
loosq/middle.messenger.praktikum.yandex pull request #3
Opened 2022-05-10 16:03 UTC by loosq

2022-05-10 18:16 UTC, podlovchenko requested changes
Привет
Пр чеки упали, не хватает пакета `@parcel/config-default`
Локально проект собирается с ошибками
В файле server.ts неправильное использование BUILD_PATH и port, проект запустила после того как руками прописала
По работе системы:
- Нет валидации данных по focus/blur при редактировании профиля
- При обновлении страницы Cannot GET /messenger
На нетлифае старая версия

2022-05-10 18:16 UTC, podlovchenko commented on src/utils/Route.ts
> +    private _block: Block<{}> | null;
Можно было бы определить `class Block<TProps extends BlockProps = {}>` , чтобы не указывать `<{}>`

2022-05-11 13:31 UTC, loosq commented on src/api/chats/Chats.ts
> +    create(data: NewChat): Promise<unknown> {
Добавил в апишку

2022-05-11 13:46 UTC, loosq commented on src/pages/chat/fragments/chatHeader/chatHeader.css
> +  background: #eaeaea;
часто цвет используется, вынес в рутовые переменные

2022-05-11 13:47 UTC, loosq commented on src/utils/HttpTransport.ts
> +    static API_URL = 'https://ya-praktikum.tech/api/v2';
по примеру из воркшопа делал, поправлю

2022-05-11 13:49 UTC, loosq commented on src/utils/Route.ts
> +    private _block: Block<{}> | null;
хорошая идея, добавил

2022-05-11 21:25 UTC, loosq commented
_Пр чеки упали, не хватает пакета @parcel/config-default_ - странно, какой пакет его требует?
_Локально проект собирается с ошибками_ - я на убунте собираю, попробую завтра на винде, если будут ошибки, напиши пожалуйста какие если не сложно
_В файле server.ts неправильное использование BUILD_PATH и port, проект запустила после того как руками прописала_ - поправил импорт
По работе системы:

_Нет валидации данных по focus/blur при редактировании профиля_ - поправил
_При обновлении страницы Cannot GET /messenger_ - поправил, должно работать 
_На нетлифае старая версия_ - поправил
_Совсем нет тестов, перенесено на 4 спринт?_ - угу

2022-05-12 07:28 UTC, loosq commented on src/utils/userTransfrom.ts
> +        }
спасибо, добавил

2022-05-12 07:35 UTC, podlovchenko commented on src/api/user/types.ts
> +    id: string | number,
Определить отдельный тип `type entityId = string | number;` и использовать его в проекте

2022-05-12 07:43 UTC, podlovchenko commented
Если напротив упавшего чека откроешь Details там будут логи
<img width="860" alt="Снимок экрана 2022-05-12 в 10 36 49" src="https://user-images.githubusercontent.com/22602747/168017267-472a8deb-206d-454f-ae8b-1b9f852beb50.png">

После внесения правок собралось без ошибок

Работу принимаю, но  поправь, пожалуйста, пр чеки

2022-05-12 10:13 UTC, loosq commented
Чеки падают на отсутствии моки, `No mocha in package.json` Можно я в след спринте добавлю?

2022-05-12 10:19 UTC, podlovchenko commented
Хорошо

2022-05-16 12:06 UTC, merged